version: '3.8'

services:
  web:
    build: .
    ports:
      - "2346:2346"
    volumes:
      - .:/app        
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=dualnback.settings
    restart: always    

  redis:
    image: redis:alpine
    restart: always
