# Generated by Django 5.2 on 2025-05-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='sequence',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
