# Generated by Django 5.2 on 2025-05-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameroom_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='guest_total_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='host_total_answered',
            field=models.IntegerField(default=0),
        ),
    ]
