# Generated by Django 5.2 on 2025-05-05 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameroom_guest_ready_gameroom_host_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
