# Generated by Django 5.2 on 2025-05-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gameroom_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='delay',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='length',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='n_back',
            field=models.IntegerField(default=2),
        ),
    ]
